name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - windows-2019

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: git-remote-swap-${{ matrix.os }}
        path: |
          target/release/git-remote-swap
          target/release/git-remote-swap.exe
